from accim.sim import accis
accis.addAccis(
    ScriptType='vrf_mm',
    SupplyAirTempInputMethod='temperature difference',
    Output_keep_existing=False,
    Output_type='standard',
    Output_freqs=['hourly'],
    Output_gen_dataframe=False,
    EnergyPlus_version='23.1',
    TempCtrl='temperature',
    ComfStand=[2, 14, 22],
    CoolSeasonStart='01/12',
    CoolSeasonEnd='28/02',
    CAT=[80, 3],
    ComfMod=[0, 3],
    SetpointAcc=1000,
    HVACmode=[2],
    VentCtrl=[0],
    VSToffset=[0],
    MinOToffset=[50],
    MaxWindSpeed=[50],
    ASTtol_steps=0.1,
    ASTtol_start=0.1,
    ASTtol_end_input=0.1,
    confirmGen=True,
)
