from accim.sim import accis
accis.addAccis(ScriptType='ex_ac',
               Outputs='standard',
               EnergyPlus_version='ep95',
               AdapStand=[1],
               CAT=[2],
               ComfMod=[3],
               HVACmode=[2],
               VentCtrl=[1],
               VSToffset=[0],
               MinOToffset=[0],
               MaxWindSpeed=[0],
               ASTtol_steps=0.1,
               ASTtol_start=0.1,
               ASTtol_end_input=0.1,
               confirmGen=True)