# accim - Adaptive-Comfort-Control-Implemented Model
# Auto-generated setAST logic
def get_SetAST_lines(ComfStand, ComfMod):
    lines = []
    if (ComfStand == 99) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*m+n+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*m+n+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*m+n+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 99) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*m+n+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*m+n+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*m+n+AHSToffset+AHSTtol')
        lines.append('endif')
    if ComfStand == 0:
        lines.append('if (ComfStand == 0) && (CurrentTime < 8)')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('set AHST = 17+AHSTtol')
        lines.append('elseif (ComfStand == 0) && (CurrentTime < 16)')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif (ComfStand == 0) && (CurrentTime < 23)')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif (ComfStand == 0) && (CurrentTime < 24)')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('set AHST = 17+AHSTtol')
        lines.append('endif')
    if (ComfStand == 1) and (ComfMod == 0):
        lines.append('if CoolingSeason == 1')
        lines.append('if (CAT==1)')
        lines.append('set ACST = 25.5+ACSTtol')
        lines.append('elseif (CAT==2)')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('elseif (CAT==3)')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (CAT==1)')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif (CAT==2)')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif (CAT==3)')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 1) and (ComfMod == 0):
        lines.append('if CoolingSeason == 1')
        lines.append('if (CAT==1)')
        lines.append('set AHST = 23.5+AHSTtol')
        lines.append('elseif (CAT==2)')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('elseif (CAT==3)')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (CAT==1)')
        lines.append('set AHST = 21+AHSTtol')
        lines.append('elseif (CAT==2)')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif (CAT==3)')
        lines.append('set AHST = 18+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 1) and (ComfMod == 1):
        lines.append('if (RMOT >= ACSTall) && (RMOT <= ACSTaul)')
        lines.append('set ACST = RMOT*0.33+18.8+ACSToffset+ACSTtol')
        lines.append('elseif CurrentTime < 7')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('elseif CurrentTime < 15')
        lines.append('set ACST = 50')
        lines.append('elseif CurrentTime < 23')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif CurrentTime < 24')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
    if (ComfStand == 1) and (ComfMod == 1):
        lines.append('if (RMOT >= AHSTall) && (RMOT <= AHSTaul)')
        lines.append('set AHST = RMOT*0.33+18.8+AHSToffset+AHSTtol')
        lines.append('elseif CurrentTime < 7')
        lines.append('set AHST = 17+AHSTtol')
        lines.append('elseif CurrentTime < 23')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif CurrentTime < 24')
        lines.append('set AHST = 17+AHSTtol')
        lines.append('endif')
    if (ComfStand == 1) and (ComfMod == 2):
        lines.append('if (RMOT >= ACSTall) && (RMOT <= ACSTaul)')
        lines.append('set ACST = RMOT*0.33+18.8+ACSToffset+ACSTtol')
        lines.append('elseif (RMOT < ACSTall) && (CAT==1)')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif (RMOT > ACSTaul) && (CAT==1)')
        lines.append('set ACST = 25.5+ACSTtol')
        lines.append('elseif (RMOT < ACSTall) && (CAT==2)')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif (RMOT > ACSTaul) && (CAT==2)')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('elseif (RMOT < ACSTall) && (CAT==3)')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif (RMOT > ACSTaul) && (CAT==3)')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
    if (ComfStand == 1) and (ComfMod == 2):
        lines.append('if (RMOT >= AHSTall) && (RMOT <= AHSTaul)')
        lines.append('set AHST = RMOT*0.33+18.8+AHSToffset+AHSTtol')
        lines.append('elseif (RMOT < AHSTall) && (CAT==1)')
        lines.append('set AHST = 21+AHSTtol')
        lines.append('elseif (RMOT > AHSTaul) && (CAT==1)')
        lines.append('set AHST = 23.5+AHSTtol')
        lines.append('elseif (RMOT < AHSTall) && (CAT==2)')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif (RMOT > AHSTaul) && (CAT==2)')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('elseif (RMOT < AHSTall) && (CAT==3)')
        lines.append('set AHST = 18+AHSTtol')
        lines.append('elseif (RMOT > AHSTaul) && (CAT==3)')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
    if (ComfStand == 1) and (ComfMod == 3):
        lines.append('if (RMOT >= ACSTall) && (RMOT <= ACSTaul)')
        lines.append('set ACST = RMOT*0.33+18.8+ACSToffset+ACSTtol')
        lines.append('elseif RMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.33+18.8+ACSToffset+ACSTtol')
        lines.append('elseif RMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.33+18.8+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 1) and (ComfMod == 3):
        lines.append('if (RMOT >= AHSTall) && (RMOT <= AHSTaul)')
        lines.append('set AHST = RMOT*0.33+18.8+AHSToffset+AHSTtol')
        lines.append('elseif RMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.33+18.8+AHSToffset+AHSTtol')
        lines.append('elseif RMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.33+18.8+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 2) and (ComfMod == 0):
        lines.append('if CoolingSeason == 1')
        lines.append('if (CAT==80)')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('elseif (CAT==90)')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (CAT==80)')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif (CAT==90)')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 2) and (ComfMod == 0):
        lines.append('if CoolingSeason == 1')
        lines.append('if (CAT==80)')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('elseif (CAT==90)')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (CAT==80)')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif (CAT==90)')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 2) and (ComfMod == 1):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.31+17.8+ACSToffset+ACSTtol')
        lines.append('elseif CurrentTime < 7')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('elseif CurrentTime < 15')
        lines.append('set ACST = 50')
        lines.append('elseif CurrentTime < 23')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif CurrentTime < 24')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
    if (ComfStand == 2) and (ComfMod == 1):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.31+17.8+AHSToffset+AHSTtol')
        lines.append('elseif CurrentTime < 7')
        lines.append('set AHST = 17+AHSTtol')
        lines.append('elseif CurrentTime < 23')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif CurrentTime < 24')
        lines.append('set AHST = 17+AHSTtol')
        lines.append('endif')
    if (ComfStand == 2) and (ComfMod == 2):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.31+17.8+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 2) and (ComfMod == 2):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.31+17.8+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 2) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.31+17.8+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.31+17.8+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.31+17.8+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 2) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.31+17.8+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.31+17.8+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.31+17.8+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 3) and (ComfMod == 0):
        lines.append('if (CAT==80)')
        lines.append('set ACST = 28+ACSTtol')
        lines.append('elseif (CAT==90)')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
    if (ComfStand == 3) and (ComfMod == 0):
        lines.append('if (CAT==80)')
        lines.append('set AHST = 18+AHSTtol')
        lines.append('elseif (CAT==90)')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('endif')
    if (ComfStand == 3) and (ComfMod == 1):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.48+14.4+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 28+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 28+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 3) and (ComfMod == 1):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.48+14.4+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 18+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 18+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 3) and (ComfMod == 2):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.48+14.4+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 3) and (ComfMod == 2):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.48+14.4+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 3) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.48+14.4+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.48+14.4+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.48+14.4+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 3) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.48+14.4+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.48+14.4+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.48+14.4+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 4) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('if CAT == 1')
        lines.append('set ACST = PMOT*0.77+12.04+ACSTtol')
        lines.append('elseif CAT == 2')
        lines.append('set ACST = PMOT*0.73+15.28+ACSTtol')
        lines.append('endif')
        lines.append('elseif PMOT < ACSTall')
        lines.append('if CAT == 1')
        lines.append('set ACST = ACSTall*0.77+12.04+ACSTtol')
        lines.append('elseif CAT == 2')
        lines.append('set ACST = ACSTall*0.73+15.28+ACSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('if CAT == 1')
        lines.append('set ACST = ACSTaul*0.77+12.04+ACSTtol')
        lines.append('elseif CAT == 2')
        lines.append('set ACST = ACSTaul*0.73+15.28+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 4) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('if CAT == 1')
        lines.append('set AHST = PMOT*0.87+2.76+AHSTtol')
        lines.append('elseif CAT == 2')
        lines.append('set AHST = PMOT*0.91-0.48+AHSTtol')
        lines.append('endif')
        lines.append('elseif PMOT < AHSTall')
        lines.append('if CAT == 1')
        lines.append('set AHST = AHSTall*0.87+2.76+AHSTtol')
        lines.append('elseif CAT == 2')
        lines.append('set AHST = AHSTall*0.91-0.48+AHSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('if CAT == 1')
        lines.append('set AHST = AHSTaul*0.87+2.76+AHSTtol')
        lines.append('elseif CAT == 2')
        lines.append('set AHST = AHSTaul*0.91-0.48+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 5) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('if CAT == 1')
        lines.append('set ACST = PMOT*0.77+9.34+ACSTtol')
        lines.append('elseif CAT == 2')
        lines.append('set ACST = PMOT*0.73+12.72+ACSTtol')
        lines.append('endif')
        lines.append('elseif PMOT < ACSTall')
        lines.append('if CAT == 1')
        lines.append('set ACST = ACSTall*0.77+9.34+ACSTtol')
        lines.append('elseif CAT == 2')
        lines.append('set ACST = ACSTall*0.73+12.72+ACSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('if CAT == 1')
        lines.append('set ACST = ACSTaul*0.77+9.34+ACSTtol')
        lines.append('elseif CAT == 2')
        lines.append('set ACST = ACSTaul*0.73+12.72+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 5) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('if CAT == 1')
        lines.append('set AHST = PMOT*0.87-0.31+AHSTtol')
        lines.append('elseif CAT == 2')
        lines.append('set AHST = PMOT*0.91-3.69+AHSTtol')
        lines.append('endif')
        lines.append('elseif PMOT < AHSTall')
        lines.append('if CAT == 1')
        lines.append('set AHST = AHSTall*0.87-0.31+AHSTtol')
        lines.append('elseif CAT == 2')
        lines.append('set AHST = AHSTall*0.91-3.69+AHSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('if CAT == 1')
        lines.append('set AHST = AHSTaul*0.87-0.31+AHSTtol')
        lines.append('elseif CAT == 2')
        lines.append('set AHST = AHSTaul*0.91-3.69+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 6) and (ComfMod == 2):
        lines.append('if CAT==80')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.30+25.9+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.30+23.6+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 6) and (ComfMod == 2):
        lines.append('if CAT==80')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.30+25.9+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.30+23.6+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 6) and (ComfMod == 3):
        lines.append('if CAT == 80')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.30+25.9+ACSTtol')
        lines.append('elseif (PMOT < ACSTall)')
        lines.append('set ACST = ACSTall*0.30+25.9+ACSTtol')
        lines.append('elseif (PMOT > ACSTaul)')
        lines.append('set ACST = ACSTaul*0.30+25.9+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT == 90')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.30+23.6+ACSTtol')
        lines.append('elseif (PMOT < ACSTall)')
        lines.append('set ACST = ACSTall*0.30+23.6+ACSTtol')
        lines.append('elseif (PMOT > ACSTaul)')
        lines.append('set ACST = ACSTaul*0.30+23.6+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 6) and (ComfMod == 3):
        lines.append('if CAT == 80')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.32+14.88+AHSTtol')
        lines.append('elseif (PMOT < AHSTall)')
        lines.append('set AHST = AHSTall*0.32+14.88+AHSTtol')
        lines.append('elseif (PMOT > AHSTaul)')
        lines.append('set AHST = AHSTaul*0.32+14.88+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT == 90')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.31+17.14+AHSTtol')
        lines.append('elseif (PMOT < AHSTall)')
        lines.append('set AHST = AHSTall*0.31+17.14+AHSTtol')
        lines.append('elseif (PMOT > AHSTaul)')
        lines.append('set AHST = AHSTaul*0.31+17.14+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if ComfStand == 7 or ComfStand == 8 or ComfStand == 9 or ComfStand == 10:
        if (ComfMod == 0):
            lines.append('if CAT==80')
            lines.append('set ACST = PMOT*0.078+23.25+2.72+ACSTtol')
            lines.append('elseif CAT==85')
            lines.append('set ACST = PMOT*0.078+23.25+2.11+ACSTtol')
            lines.append('elseif CAT==90')
            lines.append('set ACST = PMOT*0.078+23.25+1.5+ACSTtol')
            lines.append('endif')
    if ComfStand == 7 or ComfStand == 8 or ComfStand == 9 or ComfStand == 10:
        if (ComfMod == 0):
            lines.append('if CAT==80')
            lines.append('set AHST = PMOT*0.078+23.25-2.72+AHSTtol')
            lines.append('elseif CAT==85')
            lines.append('set AHST = PMOT*0.078+23.25-2.11+AHSTtol')
            lines.append('elseif CAT==90')
            lines.append('set AHST = PMOT*0.078+23.25-1.5+AHSTtol')
            lines.append('endif')
    if (ComfStand == 7) and (ComfMod == 1):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.54+12.83+ACSToffset+ACSTtol')
        lines.append('else')
        lines.append('if CAT==80')
        lines.append('set ACST = PMOT*0.078+23.25+2.72+ACSTtol')
        lines.append('elseif CAT==85')
        lines.append('set ACST = PMOT*0.078+23.25+2.11+ACSTtol')
        lines.append('elseif CAT==90')
        lines.append('set ACST = PMOT*0.078+23.25+1.5+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 7) and (ComfMod == 1):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.54+12.83+AHSToffset+AHSTtol')
        lines.append('else')
        lines.append('if CAT==80')
        lines.append('set AHST = PMOT*0.078+23.25-2.72+AHSTtol')
        lines.append('elseif CAT==85')
        lines.append('set AHST = PMOT*0.078+23.25-2.11+AHSTtol')
        lines.append('elseif CAT==90')
        lines.append('set AHST = PMOT*0.078+23.25-1.5+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 7) and (ComfMod == 2):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.54+12.83+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==85')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25.72+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27.89+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 7) and (ComfMod == 2):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.54+12.83+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==85')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20.77+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 24.26+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 7) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.54+12.83+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.54+12.83+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.54+12.83+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 7) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.54+12.83+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.54+12.83+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.54+12.83+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 8) and (ComfMod == 1):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.28+17.87+ACSToffset+ACSTtol')
        lines.append('else')
        lines.append('if CAT==80')
        lines.append('set ACST = PMOT*0.078+23.25+2.72+ACSTtol')
        lines.append('elseif CAT==85')
        lines.append('set ACST = PMOT*0.078+23.25+2.11+ACSTtol')
        lines.append('elseif CAT==90')
        lines.append('set ACST = PMOT*0.078+23.25+1.5+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 8) and (ComfMod == 1):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.28+17.87+AHSToffset+AHSTtol')
        lines.append('else')
        lines.append('if CAT==80')
        lines.append('set AHST = PMOT*0.078+23.25-2.72+AHSTtol')
        lines.append('elseif CAT==85')
        lines.append('set AHST = PMOT*0.078+23.25-2.11+AHSTtol')
        lines.append('elseif CAT==90')
        lines.append('set AHST = PMOT*0.078+23.25-1.5+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 8) and (ComfMod == 2):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.28+17.87+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==85')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25.72+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27.89+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 8) and (ComfMod == 2):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.28+17.87+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==85')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20.77+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 24.26+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 8) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.28+17.87+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.28+17.87+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.28+17.87+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 8) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.28+17.87+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.28+17.87+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.28+17.87+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 9) and (ComfMod == 1):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.39+18.42+ACSToffset+ACSTtol')
        lines.append('else')
        lines.append('if CAT==80')
        lines.append('set ACST = PMOT*0.078+23.25+2.72+ACSTtol')
        lines.append('elseif CAT==90')
        lines.append('set ACST = PMOT*0.078+23.25+1.5+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 9) and (ComfMod == 1):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.39+18.42+AHSToffset+AHSTtol')
        lines.append('else')
        lines.append('if CAT==80')
        lines.append('set AHST = PMOT*0.078+23.25+2.72+AHSTtol')
        lines.append('elseif CAT==90')
        lines.append('set AHST = PMOT*0.078+23.25+1.5+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 9) and (ComfMod == 2):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.39+18.42+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 9) and (ComfMod == 2):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.39+18.42+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 9) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.39+18.42+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.39+18.42+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.39+18.42+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 9) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.39+18.42+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.39+18.42+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.39+18.42+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 10) and (ComfMod == 1):
        lines.append('if (RMOT >= ACSTall) && (RMOT <= ACSTaul)')
        lines.append('set ACST = RMOT*0.42+17.6+ACSToffset+ACSTtol')
        lines.append('else')
        lines.append('if CAT==80')
        lines.append('set ACST = RMOT*0.078+23.25+2.72+ACSTtol')
        lines.append('elseif CAT==90')
        lines.append('set ACST = RMOT*0.078+23.25+1.5+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 10) and (ComfMod == 1):
        lines.append('if (RMOT >= AHSTall) && (RMOT <= AHSTaul)')
        lines.append('set AHST = RMOT*0.42+17.6+AHSToffset+AHSTtol')
        lines.append('else')
        lines.append('if CAT==80')
        lines.append('set AHST = RMOT*0.078+23.25-2.72+AHSTtol')
        lines.append('elseif CAT==90')
        lines.append('set AHST = RMOT*0.078+23.25-1.5+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 10) and (ComfMod == 2):
        lines.append('if (RMOT >= ACSTall) && (RMOT <= ACSTaul)')
        lines.append('set ACST = RMOT*0.42+17.6+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if RMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif RMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if RMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif RMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 10) and (ComfMod == 2):
        lines.append('if (RMOT >= AHSTall) && (RMOT <= AHSTaul)')
        lines.append('set AHST = RMOT*0.42+17.6+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if RMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif RMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if RMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif RMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 10) and (ComfMod == 3):
        lines.append('if (RMOT >= ACSTall) && (RMOT <= ACSTaul)')
        lines.append('set ACST = RMOT*0.42+17.6+ACSToffset+ACSTtol')
        lines.append('elseif RMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.42+17.6+ACSToffset+ACSTtol')
        lines.append('elseif RMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.42+17.6+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 10) and (ComfMod == 3):
        lines.append('if (RMOT >= AHSTall) && (RMOT <= AHSTaul)')
        lines.append('set AHST = RMOT*0.42+17.6+AHSToffset+AHSTtol')
        lines.append('elseif RMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.42+17.6+AHSToffset+AHSTtol')
        lines.append('elseif RMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.42+17.6+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 11) and (ComfMod == 1):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.75+5.37+ACSToffset+ACSTtol')
        lines.append('else')
        lines.append('if CAT==80')
        lines.append('set ACST = PMOT*0.078+23.25+2.72+ACSTtol')
        lines.append('elseif CAT==90')
        lines.append('set ACST = PMOT*0.078+23.25+1.5+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 11) and (ComfMod == 1):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.75+5.37+AHSToffset+AHSTtol')
        lines.append('else')
        lines.append('if CAT==80')
        lines.append('set AHST = PMOT*0.078+23.25-2.72+AHSTtol')
        lines.append('elseif CAT==90')
        lines.append('set AHST = PMOT*0.078+23.25-1.5+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 11) and (ComfMod == 2):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.75+5.37+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 11) and (ComfMod == 2):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.75+5.37+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 11) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.75+5.37+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.75+5.37+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.75+5.37+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 11) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.75+5.37+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.75+5.37+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.75+5.37+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 12) and (ComfMod == 0):
        lines.append('if (CAT==80)')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('elseif (CAT==90)')
        lines.append('set ACST = 25.5+ACSTtol')
        lines.append('endif')
    if (ComfStand == 12) and (ComfMod == 0):
        lines.append('if (CAT==80)')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif (CAT==90)')
        lines.append('set AHST = 21.5+AHSTtol')
        lines.append('endif')
    if (ComfStand == 12) and (ComfMod == 1):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.25+19.7+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25.5+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 25.5+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 12) and (ComfMod == 1):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.25+19.7+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 21.5+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 21.5+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 12) and (ComfMod == 2):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.25+19.7+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 12) and (ComfMod == 2):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.25+19.7+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 12) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.25+19.7+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.25+19.7+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.25+19.7+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 12) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.25+19.7+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.25+19.7+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.25+19.7+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 13) or (ComfStand == 14):
        lines.append('if (CAT==80)')
        lines.append('if (CurrentTime > 6) && (CurrentTime < 23)')
        if (ComfMod == 0.1):
            lines.append('set ACST = 27+ACSTtol')
        elif (ComfMod == 0.2):
            lines.append('set ACST = 26+ACSTtol')
        elif (ComfMod == 0.3):
            lines.append('set ACST = 25+ACSTtol')
        elif (ComfMod == 0.4):
            lines.append('set ACST = 24+ACSTtol')
        elif (ComfMod == 0.5):
            lines.append('set ACST = 23+ACSTtol')
        lines.append('else')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('endif')
        lines.append('elseif (CAT==90)')
        lines.append('if (CurrentTime > 6) && (CurrentTime < 23)')
        if (ComfMod == 0.1):
            lines.append('set ACST = 26+ACSTtol')
        elif (ComfMod == 0.2):
            lines.append('set ACST = 25+ACSTtol')
        elif (ComfMod == 0.3):
            lines.append('set ACST = 24+ACSTtol')
        elif (ComfMod == 0.4):
            lines.append('set ACST = 23+ACSTtol')
        elif (ComfMod == 0.5):
            lines.append('set ACST = 22+ACSTtol')
        lines.append('else')
        lines.append('set ACST = 23+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 13) or (ComfStand == 14):
        if (ComfMod == 0.1) or (ComfMod == 0.2) or (ComfMod == 0.3) or (ComfMod == 0.4) or (ComfMod == 0.5):
            lines.append('if (CAT==80)')
            lines.append('if (CurrentTime >6) && (CurrentTime < 12)')
            lines.append('set AHST = 20+AHSTtol')
            lines.append('else')
            lines.append('set AHST = 18+AHSTtol')
            lines.append('endif')
            lines.append('elseif (CAT==90)')
            lines.append('if (CurrentTime >6) && (CurrentTime < 12)')
            lines.append('set AHST = 21+AHSTtol')
            lines.append('else')
            lines.append('set AHST = 19+AHSTtol')
            lines.append('endif')
            lines.append('endif')
    if (ComfStand == 13):
        if (ComfMod == 1.1) or (ComfMod == 1.2) or (ComfMod == 1.3) or (ComfMod == 1.4) or (ComfMod == 1.5):
            lines.append('if CAT == 80')
            lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
            lines.append('set ACST = PMOT*0.26+15.9+ACSToffset+ACSTtol')
            lines.append('elseif (PMOT < ACSTall) || (PMOT > ACSTaul)')
            lines.append('if (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.1)')
            lines.append('set ACST = 27+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.2)')
            lines.append('set ACST = 26+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.3)')
            lines.append('set ACST = 25+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.4)')
            lines.append('set ACST = 24+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.5)')
            lines.append('set ACST = 23+ACSTtol')
            lines.append('else')
            lines.append('set ACST = 24+ACSTtol')
            lines.append('endif')
            lines.append('endif')
            lines.append('elseif CAT==90')
            lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
            lines.append('set ACST = PMOT*0.26+15.9+ACSToffset+ACSTtol')
            lines.append('elseif (PMOT < ACSTall) || (PMOT > ACSTaul)')
            lines.append('if (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.1)')
            lines.append('set ACST = 26+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.2)')
            lines.append('set ACST = 25+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.3)')
            lines.append('set ACST = 24+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.4)')
            lines.append('set ACST = 23+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.5)')
            lines.append('set ACST = 22+ACSTtol')
            lines.append('else')
            lines.append('set ACST = 23+ACSTtol')
            lines.append('endif')
            lines.append('endif')
            lines.append('endif')
    if (ComfStand == 13):
        if (ComfMod == 1.1) or (ComfMod == 1.2) or (ComfMod == 1.3) or (ComfMod == 1.4) or (ComfMod == 1.5):
            lines.append('if CAT == 80')
            lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
            lines.append('set AHST = PMOT*0.26+15.9+AHSToffset+AHSTtol')
            lines.append('elseif (PMOT < AHSTall) || (PMOT > AHSTaul)')
            lines.append('if (CurrentTime >6) && (CurrentTime < 12)')
            lines.append('set AHST = 20+AHSTtol')
            lines.append('else')
            lines.append('set AHST = 18+AHSTtol')
            lines.append('endif')
            lines.append('endif')
            lines.append('elseif CAT==90')
            lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
            lines.append('set AHST = PMOT*0.26+15.9+AHSToffset+AHSTtol')
            lines.append('elseif (PMOT < AHSTall) || (PMOT > AHSTaul)')
            lines.append('if (CurrentTime >6) && (CurrentTime < 12)')
            lines.append('set AHST = 21+AHSTtol')
            lines.append('else')
            lines.append('set AHST = 19+AHSTtol')
            lines.append('endif')
            lines.append('endif')
            lines.append('endif')
    if (ComfStand == 13) and (ComfMod == 2):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.26+15.9+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 13) and (ComfMod == 2):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.26+15.9+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 13) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.26+15.9+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.26+15.9+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.26+15.9+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 13) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.26+15.9+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.26+15.9+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.26+15.9+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 14):
        if (ComfMod == 1.1) or (ComfMod == 1.2) or (ComfMod == 1.3) or (ComfMod == 1.4) or (ComfMod == 1.5):
            lines.append('if CAT == 80')
            lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
            lines.append('set ACST = PMOT*0.26+16.75+ACSToffset+ACSTtol')
            lines.append('elseif (PMOT < ACSTall) || (PMOT > ACSTaul)')
            lines.append('if (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.1)')
            lines.append('set ACST = 27+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.2)')
            lines.append('set ACST = 26+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.3)')
            lines.append('set ACST = 25+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.4)')
            lines.append('set ACST = 24+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.5)')
            lines.append('set ACST = 23+ACSTtol')
            lines.append('else')
            lines.append('set ACST = 24+ACSTtol')
            lines.append('endif')
            lines.append('endif')
            lines.append('elseif CAT==90')
            lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
            lines.append('set ACST = PMOT*0.26+16.75+ACSToffset+ACSTtol')
            lines.append('elseif (PMOT < ACSTall) || (PMOT > ACSTaul)')
            lines.append('if (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.1)')
            lines.append('set ACST = 26+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.2)')
            lines.append('set ACST = 25+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.3)')
            lines.append('set ACST = 24+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.4)')
            lines.append('set ACST = 23+ACSTtol')
            lines.append('elseif (CurrentTime > 6) && (CurrentTime < 23) && (ComfMod == 1.5)')
            lines.append('set ACST = 22+ACSTtol')
            lines.append('else')
            lines.append('set ACST = 23+ACSTtol')
            lines.append('endif')
            lines.append('endif')
            lines.append('endif')
    if (ComfStand == 14):
        if (ComfMod == 1.1) or (ComfMod == 1.2) or (ComfMod == 1.3) or (ComfMod == 1.4) or (ComfMod == 1.5):
            lines.append('if CAT == 80')
            lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
            lines.append('set AHST = PMOT*0.26+16.75+AHSToffset+AHSTtol')
            lines.append('elseif (PMOT < AHSTall) || (PMOT > AHSTaul)')
            lines.append('if (CurrentTime >6) && (CurrentTime < 12)')
            lines.append('set AHST = 20+AHSTtol')
            lines.append('else')
            lines.append('set AHST = 18+AHSTtol')
            lines.append('endif')
            lines.append('endif')
            lines.append('elseif CAT==90')
            lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
            lines.append('set AHST = PMOT*0.26+16.75+AHSToffset+AHSTtol')
            lines.append('elseif (PMOT < AHSTall) || (PMOT > AHSTaul)')
            lines.append('if (CurrentTime >6) && (CurrentTime < 12)')
            lines.append('set AHST = 21+AHSTtol')
            lines.append('else')
            lines.append('set AHST = 19+AHSTtol')
            lines.append('endif')
            lines.append('endif')
            lines.append('endif')
    if (ComfStand == 14) and (ComfMod == 2):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.26+16.75+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 14) and (ComfMod == 2):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.26+16.75+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 14) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.26+16.75+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.26+16.75+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.26+16.75+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 14) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.26+16.75+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.26+16.75+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.26+16.75+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 15) or (ComfStand == 16):
        if (ComfMod == 0):
            lines.append('if (CAT==80)')
            lines.append('if PMOT < 20')
            lines.append('set ACST = 23.5+ACSTtol')
            lines.append('set AHST = 21+ACSTtol')
            lines.append('else')
            lines.append('set ACST = 25.5+ACSTtol')
            lines.append('set AHST = 22.5+ACSTtol')
            lines.append('endif')
            lines.append('elseif (CAT==90)')
            lines.append('if PMOT < 20')
            lines.append('set ACST = 23+ACSTtol')
            lines.append('set AHST = 21.5+ACSTtol')
            lines.append('else')
            lines.append('set ACST = 25+ACSTtol')
            lines.append('set AHST = 23+ACSTtol')
            lines.append('endif')
            lines.append('endif')
    if (ComfStand == 15) and (ComfMod == 1):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.56+12.74+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 23.5+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 25.5+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 23+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 15) and (ComfMod == 1):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.56+12.74+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 21+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22.5+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 15) and (ComfMod == 2):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.56+12.74+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 15) and (ComfMod == 2):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.56+12.74+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 15) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.56+12.74+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.56+12.74+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.56+12.74+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 15) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.56+12.74+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.56+12.74+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.56+12.74+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 16) and (ComfMod == 1):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.09+22.32+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 23.5+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 25.5+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 23+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 16) and (ComfMod == 1):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.09+22.32+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 21+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22.5+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 16) and (ComfMod == 2):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.09+22.32+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 16) and (ComfMod == 2):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.09+22.32+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 16) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.09+22.32+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.09+22.32+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.09+22.32+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 16) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.09+22.32+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.09+22.32+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.09+22.32+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 17) or (ComfStand == 18) or (ComfStand == 19) or (ComfStand == 20):
        if ComfMod == 0:
            lines.append('set ACST = 25+ACSTtol')
            lines.append('set AHST = 20+AHSTtol')
    if (ComfStand == 17) and (ComfMod == 1):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.48+13.9+ACSToffset+ACSTtol')
        lines.append('else')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.59+9.6+ACSToffset+ACSTtol')
        lines.append('else')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 17) and (ComfMod == 1):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.48+13.9+AHSToffset+AHSTtol')
        lines.append('else')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.59+9.6+AHSToffset+AHSTtol')
        lines.append('else')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 17) and (ComfMod == 2):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.48+13.9+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('if CAT == 90')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('if CAT == 90')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.59+9.6+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('if CAT == 90')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('if CAT == 90')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 17) and (ComfMod == 2):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.48+13.9+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('if CAT == 90')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('if CAT == 90')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.59+9.6+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('if CAT == 90')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('if CAT == 90')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 17) and (ComfMod == 3):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.48+13.9+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.48+13.9+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.48+13.9+ACSToffset+ACSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.59+9.6+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.59+9.6+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.59+9.6+ACSToffset+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 17) and (ComfMod == 3):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.48+13.9+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.48+13.9+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.48+13.9+AHSToffset+AHSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.59+9.6+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.59+9.6+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.59+9.6+AHSToffset+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 18) and (ComfMod == 1):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.84+5.3+ACSToffset+ACSTtol')
        lines.append('else')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.96-3.6+ACSToffset+ACSTtol')
        lines.append('else')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 18) and (ComfMod == 1):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.84+5.3+AHSToffset+AHSTtol')
        lines.append('else')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.96-3.6+AHSToffset+AHSTtol')
        lines.append('else')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 18) and (ComfMod == 2):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.84+5.3+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('if CAT == 90')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('if CAT == 90')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.96-3.6+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('if CAT == 90')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('if CAT == 90')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 18) and (ComfMod == 2):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.84+5.3+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('if CAT == 90')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('if CAT == 90')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.96-3.6+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('if CAT == 90')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('if CAT == 90')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 18) and (ComfMod == 3):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.84+5.3+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.84+5.3+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.84+5.3+ACSToffset+ACSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.96-3.6+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.96-3.6+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.96-3.6+ACSToffset+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 18) and (ComfMod == 3):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.84+5.3+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.84+5.3+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.84+5.3+AHSToffset+AHSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.96-3.6+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.96-3.6+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.96-3.6+AHSToffset+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 19) and (ComfMod == 1):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.27+17.9+ACSToffset+ACSTtol')
        lines.append('else')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.53+10.3+ACSToffset+ACSTtol')
        lines.append('else')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 19) and (ComfMod == 1):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.27+17.9+AHSToffset+AHSTtol')
        lines.append('else')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.53+10.3+AHSToffset+AHSTtol')
        lines.append('else')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 19) and (ComfMod == 2):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.27+17.9+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('if CAT == 90')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('if CAT == 90')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.53+10.3+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('if CAT == 90')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('if CAT == 90')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 19) and (ComfMod == 2):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.27+17.9+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('if CAT == 90')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('if CAT == 90')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.53+10.3+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('if CAT == 90')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('if CAT == 90')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 19) and (ComfMod == 3):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.27+17.9+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.27+17.9+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.27+17.9+ACSToffset+ACSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.53+10.3+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.53+10.3+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.53+10.3+ACSToffset+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 19) and (ComfMod == 3):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.27+17.9+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.27+17.9+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.27+17.9+AHSToffset+AHSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.53+10.3+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.53+10.3+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.53+10.3+AHSToffset+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 20) and (ComfMod == 1):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.38+15.7+ACSToffset+ACSTtol')
        lines.append('else')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.47+9.07+ACSToffset+ACSTtol')
        lines.append('else')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 20) and (ComfMod == 1):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.38+15.7+AHSToffset+AHSTtol')
        lines.append('else')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.47+9.07+AHSToffset+AHSTtol')
        lines.append('else')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 20) and (ComfMod == 2):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.38+15.7+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('if CAT == 90')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('if CAT == 90')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.47+9.07+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('if CAT == 90')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('if CAT == 90')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 20) and (ComfMod == 2):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.38+15.7+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('if CAT == 90')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('if CAT == 90')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.47+9.07+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('if CAT == 90')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('endif')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('if CAT == 90')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('elseif CAT == 80')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 20) and (ComfMod == 3):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.38+15.7+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.38+15.7+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.38+15.7+ACSToffset+ACSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.47+9.07+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.47+9.07+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.47+9.07+ACSToffset+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 20) and (ComfMod == 3):
        lines.append('if (DayOfYear <= 121) || (DayOfYear > 295)')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.38+15.7+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.38+15.7+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.38+15.7+AHSToffset+AHSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.47+9.07+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.47+9.07+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.47+9.07+AHSToffset+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 21) and (ComfMod == 2):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.678+13.51+ACSToffset+ACSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 25+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 27+ACSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < ACSTall')
        lines.append('set ACST = 24+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = 26+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 21) and (ComfMod == 2):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.678+13.51+AHSToffset+AHSTtol')
        lines.append('elseif CAT==80')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 19+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 22+AHSTtol')
        lines.append('endif')
        lines.append('elseif CAT==90')
        lines.append('if PMOT < AHSTall')
        lines.append('set AHST = 20+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = 23+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 21) and (ComfMod == 3):
        lines.append('if (PMOT >= ACSTall) && (PMOT <= ACSTaul)')
        lines.append('set ACST = PMOT*0.678+13.51+ACSToffset+ACSTtol')
        lines.append('elseif PMOT < ACSTall')
        lines.append('set ACST = ACSTall*0.678+13.51+ACSToffset+ACSTtol')
        lines.append('elseif PMOT > ACSTaul')
        lines.append('set ACST = ACSTaul*0.678+13.51+ACSToffset+ACSTtol')
        lines.append('endif')
    if (ComfStand == 21) and (ComfMod == 3):
        lines.append('if (PMOT >= AHSTall) && (PMOT <= AHSTaul)')
        lines.append('set AHST = PMOT*0.678+13.51+AHSToffset+AHSTtol')
        lines.append('elseif PMOT < AHSTall')
        lines.append('set AHST = AHSTall*0.678+13.51+AHSToffset+AHSTtol')
        lines.append('elseif PMOT > AHSTaul')
        lines.append('set AHST = AHSTaul*0.678+13.51+AHSToffset+AHSTtol')
        lines.append('endif')
    if (ComfStand == 22):
        lines.append('if CoolingSeason == 1')
        lines.append('if (CAT==3)')
        lines.append('set ACST = 24.5+2.5+ACSTtol')
        lines.append('elseif (CAT==2)')
        lines.append('set ACST = 24.5+1.5+ACSTtol')
        lines.append('elseif (CAT==1)')
        lines.append('set ACST = 24.5+1+ACSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (CAT==3)')
        lines.append('set ACST = 22+3+ACSTtol')
        lines.append('elseif (CAT==2)')
        lines.append('set ACST = 22+2+ACSTtol')
        lines.append('elseif (CAT==1)')
        lines.append('set ACST = 22+1+ACSTtol')
        lines.append('endif')
        lines.append('endif')
    if (ComfStand == 22):
        lines.append('if CoolingSeason == 1')
        lines.append('if (CAT==3)')
        lines.append('set AHST = 24.5-2.5+AHSTtol')
        lines.append('elseif (CAT==2)')
        lines.append('set AHST = 24.5-1.5+AHSTtol')
        lines.append('elseif (CAT==1)')
        lines.append('set AHST = 24.5-1+AHSTtol')
        lines.append('endif')
        lines.append('else')
        lines.append('if (CAT==3)')
        lines.append('set AHST = 22-3+AHSTtol')
        lines.append('elseif (CAT==2)')
        lines.append('set AHST = 22-2+AHSTtol')
        lines.append('elseif (CAT==1)')
        lines.append('set AHST = 22-1+AHSTtol')
        lines.append('endif')
        lines.append('endif')
    lines.append('set ACSTx2 = ACST*SetpointAcc')
    lines.append('set AHSTx2 = AHST*SetpointAcc')
    lines.append('set roundedACSTx2 = @Round ACSTx2')
    lines.append('set roundedAHSTx2 = @Round AHSTx2')
    lines.append('if roundedACSTx2 - ACSTx2 < 0')
    lines.append('set ACSTroundedUp = 0')
    lines.append('else')
    lines.append('set ACSTroundedUp = 1')
    lines.append('endif')
    lines.append('if roundedAHSTx2 - AHSTx2 < 0')
    lines.append('set AHSTroundedUp = 0')
    lines.append('else')
    lines.append('set AHSTroundedUp = 1')
    lines.append('endif')
    lines.append('if ACSTroundedUp == 0')
    lines.append('set roundedACST = roundedACSTx2 / SetpointAcc')
    lines.append('else')
    lines.append('set roundedACST = (roundedACSTx2 - 1) / SetpointAcc')
    lines.append('endif')
    lines.append('if AHSTroundedUp == 0')
    lines.append('set roundedAHST = (roundedAHSTx2 + 1) / SetpointAcc')
    lines.append('else')
    lines.append('set roundedAHST = roundedAHSTx2 / SetpointAcc')
    lines.append('endif')
    return lines
